name: Run Rust Format and Clippy

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-fmt:
    name: Run fmt and clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85.1
          components: rustfmt,clippy
          cache: true
      - uses: extractions/setup-just@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Check fmt
        run: just fmt-check
      - name: Run Clippy
        run: just clippy